import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "@/context/session-context";
import { getSession } from "@/lib/auth";
import { Toaster } from "sonner";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-admin",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  return (
    <SessionProvider session={session}>
      <html lang="en" className={`${inter.className}  h-full antialiased`}>
        <body className="min-h-full flex flex-col">
          <Toaster />
          {children}
        </body>
      </html>
    </SessionProvider>
  );
}
